name: Hello

on:
  push:
    branches:
      - dev
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: print Hello
        run: echo "Hello Ziad from ${{runner.os}}"
      - name: print which branch now
        run: echo "from ${{github.ref}}"
